bool bt_passAuto
bool bt_passHand
bool bt_cancelMission
bool bt_setting
bool bt_clearError

int16 bt_moveHand

bool bt_coorAverage
bool bt_disPointA
bool bt_disPointB

bool bt_hideSetting

bool bt_setpose
bool bt_speaker
bool bt_charger
bool bt_lifter

bool bt_auxiliaryLights

int16 vs_speed
bool ck_remote

bool bt_resetFrameWork

bool bt_disableBrake
bool bt_doNextPlan
bool bt_doNextPlan2
bool bt_doNextPlanClicked

bool bt_brake
int16 soundtype
int16 ledtype
int16 toyobit
